(* ::Package:: *)

(* ::Input:: *)
(*Clear["`*"]*)
(*s=Import[NotebookDirectory[]<>"18.txt"];*)
(*t=ToExpression@StringSplit@StringSplit[s,"\n"];*)
(*n=Length@t;*)
(*f[n+1,_]:=0;*)
(*f[x_,y_]:=f[x,y]=Max[f[x+1,y],f[x+1,y+1]]+t[[x,y]]*)
(*f[1,1]*)
